###############################################################################
#                                                                             #
# Al_Th232.mac                                                                #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
# output log-file name
#/run/filename n_phantom_100000.log
#
# verbosities
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
##/dmx/draw/drawTracks noscint
/dmx/draw/drawTracks all
/dmx/draw/drawHits 0
#
# file output
/dmx/savePmt  0
/dmx/saveHits 0
#
#
# radioactive decay module
/grdm/analogueMC 1
/grdm/verbose 0
/grdm/allVolumes
#
#
# using GPS for ambe_spectrum:
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0. 0. 43.21 cm
/gps/pos/radius 12.6 cm
/gps/pos/halfz 18 cm
/gps/pos/confine contenedor_Al_phys
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#
#
#
/gps/hist/point 0 3.3705e-10
/gps/hist/point 0.1 9.53586e-09
/gps/hist/point 0.2 1.52838e-08
/gps/hist/point 0.3 1.45702e-08
/gps/hist/point 0.4 1.69005e-08
/gps/hist/point 0.5 1.85989e-08
/gps/hist/point 0.6 1.92977e-08
/gps/hist/point 0.7 1.92808e-08
/gps/hist/point 0.8 1.93887e-08
/gps/hist/point 0.9 1.63475e-08
/gps/hist/point 1 1.7468e-08
/gps/hist/point 1.1 1.81331e-08
/gps/hist/point 1.2 1.85921e-08
/gps/hist/point 1.3 1.74984e-08
/gps/hist/point 1.4 1.57383e-08
/gps/hist/point 1.5 1.61566e-08
/gps/hist/point 1.6 1.50172e-08
/gps/hist/point 1.7 1.56714e-08
/gps/hist/point 1.8 1.54512e-08
/gps/hist/point 1.9 1.51347e-08
/gps/hist/point 2 1.51892e-08
/gps/hist/point 2.1 1.36228e-08
/gps/hist/point 2.2 1.16858e-08
/gps/hist/point 2.3 1.08836e-08
/gps/hist/point 2.4 1.03702e-08
/gps/hist/point 2.5 9.23243e-09
/gps/hist/point 2.6 8.08878e-09
/gps/hist/point 2.7 7.64119e-09
/gps/hist/point 2.8 7.25744e-09
/gps/hist/point 2.9 6.26003e-09
/gps/hist/point 3 5.80678e-09
/gps/hist/point 3.1 4.6243e-09
/gps/hist/point 3.2 4.12893e-09
/gps/hist/point 3.3 3.46879e-09
/gps/hist/point 3.4 3.141e-09
/gps/hist/point 3.5 2.89909e-09
/gps/hist/point 3.6 2.07242e-09
/gps/hist/point 3.7 1.7977e-09
/gps/hist/point 3.8 1.82057e-09
/gps/hist/point 3.9 1.80939e-09
/gps/hist/point 4 1.78875e-09
/gps/hist/point 4.1 1.76264e-09
/gps/hist/point 4.2 1.67082e-09
/gps/hist/point 4.3 1.34715e-09
/gps/hist/point 4.4 9.75222e-10
/gps/hist/point 4.5 8.438e-10
/gps/hist/point 4.6 8.18245e-10
/gps/hist/point 4.7 8.02185e-10
/gps/hist/point 4.8 7.73504e-10
/gps/hist/point 4.9 6.71116e-10
/gps/hist/point 5 4.25291e-10
/gps/hist/point 5.1 1.55957e-10
/gps/hist/point 5.2 2.82666e-11
/gps/hist/point 5.3 2.32643e-12
/gps/hist/point 5.4 8.32564e-14
/gps/hist/point 5.5 1.26603e-15
/gps/hist/point 5.6 8.07477e-18
/gps/hist/point 5.7 2.14336e-20
/gps/hist/point 5.8 2.35636e-23
/gps/hist/point 5.9 1.06945e-26
/gps/hist/point 6 1.99938e-30
/gps/hist/point 6.1 1.53732e-34
/gps/hist/point 6.2 4.85578e-39
/gps/hist/point 6.3 6.30584e-44
/gps/hist/point 6.4 0
/gps/hist/point 6.5 0
/gps/hist/point 6.6 0
/gps/hist/point 6.7 0
/gps/hist/point 6.8 0
/gps/hist/point 6.9 0
/gps/hist/point 7 0
/gps/hist/point 7.1 0
/gps/hist/point 7.2 0
/gps/hist/point 7.3 0
/gps/hist/point 7.4 0
/gps/hist/point 7.5 0
/gps/hist/point 7.6 0
/gps/hist/point 7.7 0
/gps/hist/point 7.8 0
/gps/hist/point 7.9 0
/gps/hist/point 8 0
/gps/hist/point 8.1 0
/gps/hist/point 8.2 0
/gps/hist/point 8.3 0
/gps/hist/point 8.4 0
/gps/hist/point 8.5 0
/gps/hist/point 8.6 0
/gps/hist/point 8.7 0
/gps/hist/point 8.8 0
/gps/hist/point 8.9 0
/gps/hist/point 9 0
/gps/hist/point 9.1 0
/gps/hist/point 9.2 0
/gps/hist/inter Lin

/random/setSeeds 5298 19704

/dmx/hitsfile ambe_spectrum.out
/dmx/histogramfile ambe_spectrum.his

/run/beamOn 20000


