###############################################################################
#                                                                             #
# Al_U238_Low.mac                                                                #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
# output log-file name
#/run/filename n_phantom_100000.log
#
# verbosities
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
##/dmx/draw/drawTracks noscint
/dmx/draw/drawTracks all
/dmx/draw/drawHits 0
#
# file output
/dmx/savePmt  0
/dmx/saveHits 0
#
#
# radioactive decay module
/grdm/analogueMC 1
/grdm/verbose 0
/grdm/allVolumes
#
#
# using GPS for ambe_spectrum:
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0. 0. 43.21 cm
/gps/pos/radius 12.6 cm
/gps/pos/halfz 18 cm
/gps/pos/confine contenedor_Al_phys
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#
#
#
/gps/hist/point 0 1.84688e-10
/gps/hist/point 0.1 7.02663e-09
/gps/hist/point 0.2 8.12059e-09
/gps/hist/point 0.3 9.28353e-09
/gps/hist/point 0.4 1.18804e-08
/gps/hist/point 0.5 1.39586e-08
/gps/hist/point 0.6 1.35201e-08
/gps/hist/point 0.7 1.21332e-08
/gps/hist/point 0.8 1.31821e-08
/gps/hist/point 0.9 1.2825e-08
/gps/hist/point 1 1.41996e-08
/gps/hist/point 1.1 1.42864e-08
/gps/hist/point 1.2 1.303e-08
/gps/hist/point 1.3 1.16258e-08
/gps/hist/point 1.4 1.10863e-08
/gps/hist/point 1.5 1.1135e-08
/gps/hist/point 1.6 7.65276e-09
/gps/hist/point 1.7 9.47576e-09
/gps/hist/point 1.8 1.00007e-08
/gps/hist/point 1.9 9.56557e-09
/gps/hist/point 2 9.22328e-09
/gps/hist/point 2.1 6.94789e-09
/gps/hist/point 2.2 5.48381e-09
/gps/hist/point 2.3 5.69273e-09
/gps/hist/point 2.4 5.84462e-09
/gps/hist/point 2.5 5.80338e-09
/gps/hist/point 2.6 4.47646e-09
/gps/hist/point 2.7 3.11421e-09
/gps/hist/point 2.8 3.18194e-09
/gps/hist/point 2.9 2.7186e-09
/gps/hist/point 3 2.87763e-09
/gps/hist/point 3.1 2.94087e-09
/gps/hist/point 3.2 2.92334e-09
/gps/hist/point 3.3 2.67648e-09
/gps/hist/point 3.4 2.00072e-09
/gps/hist/point 3.5 1.59315e-09
/gps/hist/point 3.6 1.32435e-09
/gps/hist/point 3.7 1.33496e-09
/gps/hist/point 3.8 1.40278e-09
/gps/hist/point 3.9 1.35301e-09
/gps/hist/point 4 1.0582e-09
/gps/hist/point 4.1 4.93441e-10
/gps/hist/point 4.2 1.03763e-10
/gps/hist/point 4.3 8.40052e-12
/gps/hist/point 4.4 2.42362e-13
/gps/hist/point 4.5 2.398e-15
/gps/hist/point 4.6 7.97195e-18
/gps/hist/point 4.7 8.80084e-21
/gps/hist/point 4.8 3.20327e-24
/gps/hist/point 4.9 3.82647e-28
/gps/hist/point 5 1.49544e-32
/gps/hist/point 5.1 1.90788e-37
/gps/hist/point 5.2 7.93135e-43
/gps/hist/point 5.3 0
/gps/hist/point 5.4 0
/gps/hist/point 5.5 0
/gps/hist/point 5.6 0
/gps/hist/point 5.7 0
/gps/hist/point 5.8 0
/gps/hist/point 5.9 0
/gps/hist/point 6 0
/gps/hist/point 6.1 0
/gps/hist/point 6.2 0
/gps/hist/point 6.3 0
/gps/hist/point 6.4 0
/gps/hist/point 6.5 0
/gps/hist/point 6.6 0
/gps/hist/point 6.7 0
/gps/hist/point 6.8 0
/gps/hist/inter Lin

/random/setSeeds 5398 19704

/dmx/hitsfile ambe_spectrum.out
/dmx/histogramfile ambe_spectrum.his

/run/beamOn 20000


