###############################################################################
#                                                                             #
# Cu_Th232.mac                                                                #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
# output log-file name
#/run/filename n_phantom_100000.log
#
# verbosities
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
##/dmx/draw/drawTracks noscint
/dmx/draw/drawTracks all
/dmx/draw/drawHits 0
#
# file output
/dmx/savePmt  0
/dmx/saveHits 0
#
#
# radioactive decay module
/grdm/analogueMC 1
/grdm/verbose 0
/grdm/allVolumes
#
#
# using GPS for ambe_spectrum:
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 12.8 0. 39.3 cm
/gps/pos/radius 5 cm
/gps/pos/halfz 3 cm
/gps/pos/confine Cu_phys
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#
#
#
/gps/hist/point 0.1 1.8488e-10
/gps/hist/point 0.2 3.47286e-10
/gps/hist/point 0.3 5.58246e-10
/gps/hist/point 0.4 4.08713e-10
/gps/hist/point 0.5 3.85055e-10
/gps/hist/point 0.6 2.49122e-10
/gps/hist/point 0.7 2.05532e-10
/gps/hist/point 0.8 1.18357e-10
/gps/hist/point 0.9 1.1718e-10
/gps/hist/point 1 1.11231e-10
/gps/hist/point 1.1 1.05876e-10
/gps/hist/point 1.2 9.91212e-11
/gps/hist/point 1.3 9.18005e-11
/gps/hist/point 1.4 8.49756e-11
/gps/hist/point 1.5 7.72632e-11
/gps/hist/point 1.6 6.95349e-11
/gps/hist/point 1.7 6.28853e-11
/gps/hist/point 1.8 5.1894e-11
/gps/hist/point 1.9 4.31633e-11
/gps/hist/point 2 2.8462e-11
/gps/hist/point 2.1 1.7871e-11
/gps/hist/point 2.2 1.1649e-11
/gps/hist/point 2.3 6.34734e-12
/gps/hist/point 2.4 5.15313e-12
/gps/hist/point 2.5 3.25078e-13
/gps/hist/point 2.6 4.02629e-18
/gps/hist/point 2.7 3.3814e-27
/gps/hist/point 2.8 1.72137e-40
/gps/hist/point 2.9 0
/gps/hist/point 3 0
/gps/hist/point 3.1 0
/gps/hist/point 3.2 0
/gps/hist/point 3.3 0
/gps/hist/point 3.4 0
/gps/hist/point 3.5 0
/gps/hist/point 3.6 0
/gps/hist/point 3.7 0
/gps/hist/point 3.8 0
/gps/hist/point 3.9 0
/gps/hist/point 4 0
/gps/hist/point 4.1 0
/gps/hist/point 4.2 0
/gps/hist/point 4.3 0
/gps/hist/point 4.4 0
/gps/hist/point 4.5 0
/gps/hist/point 4.6 0
/gps/hist/point 4.7 0
/gps/hist/point 4.8 0
/gps/hist/point 4.9 0
/gps/hist/point 5 0
/gps/hist/point 5.1 0
/gps/hist/point 5.2 0
/gps/hist/point 5.3 0
/gps/hist/point 5.4 0
/gps/hist/point 5.5 0
/gps/hist/point 5.6 0
/gps/hist/point 5.7 0
/gps/hist/point 5.8 0
/gps/hist/point 5.9 0
/gps/hist/point 6 0
/gps/hist/point 6.1 0
/gps/hist/point 6.2 0
/gps/hist/point 6.3 0
/gps/hist/point 6.4 0
/gps/hist/point 6.5 0
/gps/hist/point 6.6 0
/gps/hist/point 6.7 0
/gps/hist/point 6.8 0
/gps/hist/point 6.9 0
/gps/hist/point 7 0
/gps/hist/point 7.1 0
/gps/hist/point 7.2 0
/gps/hist/point 7.3 0
/gps/hist/point 7.4 0
/gps/hist/point 7.5 0
/gps/hist/point 7.6 0
/gps/hist/point 7.7 0
/gps/hist/point 7.8 0
/gps/hist/point 7.9 0
/gps/hist/point 8 0
/gps/hist/point 8.1 0
/gps/hist/point 8.2 0
/gps/hist/point 8.3 0
/gps/hist/point 8.4 0
/gps/hist/point 8.5 0
/gps/hist/point 8.6 0
/gps/hist/point 8.7 0
/gps/hist/point 8.8 0
/gps/hist/point 8.9 0
/gps/hist/point 9 0
/gps/hist/point 9.1 0
/gps/hist/point 9.2 0
/gps/hist/point 9.3 0
/gps/hist/point 9.4 0
/gps/hist/point 9.5 0
/gps/hist/point 9.6 0
/gps/hist/point 9.7 0
/gps/hist/point 9.8 0
/gps/hist/point 9.9 0
/gps/hist/point 10 0
/gps/hist/point 10.1 0
/gps/hist/point 10.2 0
/gps/hist/point 10.3 0
/gps/hist/point 10.4 0
/gps/hist/point 10.5 0
/gps/hist/point 10.6 0
/gps/hist/inter Lin

/random/setSeeds 5298 19704

/dmx/hitsfile ambe_spectrum.out
/dmx/histogramfile ambe_spectrum.his

/run/beamOn 10000


