###############################################################################
#                                                                             #
# LED_Th232.mac                                                          #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
# output log-file name
#/run/filename n_phantom_100000.log
#
# verbosities
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
##/dmx/draw/drawTracks noscint
/dmx/draw/drawTracks all
/dmx/draw/drawHits 0
#
# file output
/dmx/savePmt  0
/dmx/saveHits 0
#
#
# radioactive decay module
/grdm/analogueMC 1
/grdm/verbose 0
/grdm/allVolumes
#
#
# using GPS for ambe_spectrum:
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0. 0. 70 cm
/gps/pos/radius 5 cm
/gps/pos/halfz 1 cm
/gps/pos/confine LED_phys
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#
#
#
/gps/hist/point 0 1.12661e-10
/gps/hist/point 0.1 4.55144e-09
/gps/hist/point 0.2 5.52771e-09
/gps/hist/point 0.3 5.64201e-09
/gps/hist/point 0.4 6.68635e-09
/gps/hist/point 0.5 7.25553e-09
/gps/hist/point 0.6 7.57043e-09
/gps/hist/point 0.7 7.64306e-09
/gps/hist/point 0.8 7.7414e-09
/gps/hist/point 0.9 6.529e-09
/gps/hist/point 1 6.92248e-09
/gps/hist/point 1.1 7.16934e-09
/gps/hist/point 1.2 7.33799e-09
/gps/hist/point 1.3 7.02142e-09
/gps/hist/point 1.4 6.5141e-09
/gps/hist/point 1.5 6.37847e-09
/gps/hist/point 1.6 6.05279e-09
/gps/hist/point 1.7 5.95708e-09
/gps/hist/point 1.8 5.89809e-09
/gps/hist/point 1.9 5.84196e-09
/gps/hist/point 2 4.85416e-09
/gps/hist/point 2.1 4.2572e-09
/gps/hist/point 2.2 3.62879e-09
/gps/hist/point 2.3 3.37583e-09
/gps/hist/point 2.4 3.218e-09
/gps/hist/point 2.5 2.86431e-09
/gps/hist/point 2.6 2.5106e-09
/gps/hist/point 2.7 2.36951e-09
/gps/hist/point 2.8 2.24907e-09
/gps/hist/point 2.9 1.938e-09
/gps/hist/point 3 1.79667e-09
/gps/hist/point 3.1 1.43212e-09
/gps/hist/point 3.2 1.27759e-09
/gps/hist/point 3.3 1.07208e-09
/gps/hist/point 3.4 9.69859e-10
/gps/hist/point 3.5 8.94845e-10
/gps/hist/point 3.6 6.40167e-10
/gps/hist/point 3.7 5.55491e-10
/gps/hist/point 3.8 5.6231e-10
/gps/hist/point 3.9 5.58552e-10
/gps/hist/point 4 5.51867e-10
/gps/hist/point 4.1 5.43505e-10
/gps/hist/point 4.2 5.14963e-10
/gps/hist/point 4.3 4.15243e-10
/gps/hist/point 4.4 3.0076e-10
/gps/hist/point 4.5 2.60181e-10
/gps/hist/point 4.6 2.52126e-10
/gps/hist/point 4.7 2.4699e-10
/gps/hist/point 4.8 2.37984e-10
/gps/hist/point 4.9 2.06355e-10
/gps/hist/point 5 1.30715e-10
/gps/hist/point 5.1 4.79234e-11
/gps/hist/point 5.2 8.6848e-12
/gps/hist/point 5.3 7.14735e-13
/gps/hist/point 5.4 2.55772e-14
/gps/hist/point 5.5 3.88926e-16
/gps/hist/point 5.6 2.48053e-18
/gps/hist/point 5.7 6.58421e-21
/gps/hist/point 5.8 7.23845e-24
/gps/hist/point 5.9 3.2852e-27
/gps/hist/point 6 6.14175e-31
/gps/hist/point 6.1 4.72237e-35
/gps/hist/point 6.2 1.4916e-39
/gps/hist/point 6.3 1.96182e-44
/gps/hist/point 6.4 0
/gps/hist/point 6.5 0
/gps/hist/point 6.6 0
/gps/hist/point 6.7 0
/gps/hist/point 6.8 0
/gps/hist/point 6.9 0
/gps/hist/point 7 0
/gps/hist/point 7.1 0
/gps/hist/point 7.2 0
/gps/hist/point 7.3 0
/gps/hist/point 7.4 0
/gps/hist/point 7.5 0
/gps/hist/point 7.6 0
/gps/hist/point 7.7 0
/gps/hist/point 7.8 0
/gps/hist/point 7.9 0
/gps/hist/point 8 0
/gps/hist/point 8.1 0
/gps/hist/point 8.2 0
/gps/hist/point 8.3 0
/gps/hist/point 8.4 0
/gps/hist/point 8.5 0
/gps/hist/point 8.6 0
/gps/hist/point 8.7 0
/gps/hist/point 8.8 0
/gps/hist/point 8.9 0
/gps/hist/point 9 0
/gps/hist/point 9.1 0
/gps/hist/point 9.2 0
/gps/hist/point 9.3 0
/gps/hist/point 9.4 0
/gps/hist/point 9.5 0
/gps/hist/point 9.6 0
/gps/hist/point 9.7 0
/gps/hist/point 9.8 0
/gps/hist/point 9.9 0
/gps/hist/point 10 0
/gps/hist/point 10.1 0
/gps/hist/point 10.2 0
/gps/hist/point 10.3 0
/gps/hist/point 10.4 0
/gps/hist/point 10.5 0
/gps/hist/point 10.6 0
/gps/hist/point 10.7 0
/gps/hist/point 10.8 0
/gps/hist/point 10.9 0
/gps/hist/point 11 0
/gps/hist/inter Lin

/random/setSeeds 5298 19704

/dmx/hitsfile ambe_spectrum.out
/dmx/histogramfile ambe_spectrum.his

/run/beamOn 20000


