###############################################################################
#                                                                             #
# LED_U238_Up.mac                                                          #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
# output log-file name
#/run/filename n_phantom_100000.log
#
# verbosities
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
##/dmx/draw/drawTracks noscint
/dmx/draw/drawTracks all
/dmx/draw/drawHits 0
#
# file output
/dmx/savePmt  0
/dmx/saveHits 0
#
#
# radioactive decay module
/grdm/analogueMC 1
/grdm/verbose 0
/grdm/allVolumes
#
#
# using GPS for ambe_spectrum:
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0. 0. 70 cm
/gps/pos/radius 5 cm
/gps/pos/halfz 1 cm
/gps/pos/confine LED_phys
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#
#
#
/gps/hist/point 0.1 2.72503e-11
/gps/hist/point 0.2 9.63267e-11
/gps/hist/point 0.3 1.2443e-10
/gps/hist/point 0.4 1.53963e-10
/gps/hist/point 0.5 2.16008e-10
/gps/hist/point 0.6 2.91901e-10
/gps/hist/point 0.7 3.5197e-10
/gps/hist/point 0.8 2.60029e-10
/gps/hist/point 0.9 2.08767e-10
/gps/hist/point 1 2.13989e-10
/gps/hist/point 1.1 2.09998e-10
/gps/hist/point 1.2 2.55122e-10
/gps/hist/point 1.3 3.04991e-10
/gps/hist/point 1.4 2.9665e-10
/gps/hist/point 1.5 1.19394e-10
/gps/hist/point 1.6 4.08577e-12
/gps/hist/point 1.7 1.40456e-15
/gps/hist/point 1.8 2.89158e-21
/gps/hist/point 1.9 3.26655e-29
/gps/hist/point 2 1.97406e-39
/gps/hist/point 2.1 0
/gps/hist/point 2.2 0
/gps/hist/point 2.3 0
/gps/hist/point 2.4 0
/gps/hist/point 2.5 0
/gps/hist/point 2.6 0
/gps/hist/point 2.7 0
/gps/hist/point 2.8 0
/gps/hist/point 2.9 0
/gps/hist/point 3 0
/gps/hist/point 3.1 0
/gps/hist/point 3.2 0
/gps/hist/point 3.3 0
/gps/hist/point 3.4 0
/gps/hist/point 3.5 0
/gps/hist/point 3.6 0
/gps/hist/point 3.7 0
/gps/hist/point 3.8 0
/gps/hist/point 3.9 0
/gps/hist/point 4 0
/gps/hist/point 4.1 0
/gps/hist/point 4.2 0
/gps/hist/point 4.3 0
/gps/hist/point 4.4 0
/gps/hist/point 4.5 0
/gps/hist/point 4.6 0
/gps/hist/point 4.7 0
/gps/hist/point 4.8 0
/gps/hist/point 4.9 0
/gps/hist/point 5 0
/gps/hist/point 5.1 0
/gps/hist/point 5.2 0
/gps/hist/point 5.3 0
/gps/hist/point 5.4 0
/gps/hist/point 5.5 0
/gps/hist/point 5.6 0
/gps/hist/point 5.7 0
/gps/hist/point 5.8 0
/gps/hist/point 5.9 0
/gps/hist/point 6 0
/gps/hist/point 6.1 0
/gps/hist/point 6.2 0
/gps/hist/point 6.3 0
/gps/hist/point 6.4 0
/gps/hist/point 6.5 0
/gps/hist/point 6.6 0
/gps/hist/point 6.7 0
/gps/hist/inter Lin

/random/setSeeds 5298 19704

/dmx/hitsfile ambe_spectrum.out
/dmx/histogramfile ambe_spectrum.his

/run/beamOn 20000


