###############################################################################
#                                                                             #
# Piezo_Th232.mac                                                             #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
# output log-file name
#/run/filename n_phantom_100000.log
#
# verbosities
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
##/dmx/draw/drawTracks noscint
/dmx/draw/drawTracks all
/dmx/draw/drawHits 0
#
# file output
/dmx/savePmt  0
/dmx/saveHits 0
#
#
# radioactive decay module
/grdm/analogueMC 1
/grdm/verbose 0
/grdm/allVolumes
#
#
# using GPS for ambe_spectrum:
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 12.8 0. 39.3 cm
/gps/pos/radius 5 cm
/gps/pos/halfz 3 cm
/gps/pos/confine Piezo_phys
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#
#
#
/gps/hist/point 0 6.96819e-11
/gps/hist/point 0.1 1.48781e-10
/gps/hist/point 0.2 1.70977e-10
/gps/hist/point 0.3 1.96779e-10
/gps/hist/point 0.4 2.1643e-10
/gps/hist/point 0.5 2.35598e-10
/gps/hist/point 0.6 2.54622e-10
/gps/hist/point 0.7 2.7121e-10
/gps/hist/point 0.8 2.82772e-10
/gps/hist/point 0.9 2.91248e-10
/gps/hist/point 1 3.10764e-10
/gps/hist/point 1.1 3.02842e-10
/gps/hist/point 1.2 3.07862e-10
/gps/hist/point 1.3 3.11211e-10
/gps/hist/point 1.4 3.18954e-10
/gps/hist/point 1.5 3.2084e-10
/gps/hist/point 1.6 3.18065e-10
/gps/hist/point 1.7 3.18223e-10
/gps/hist/point 1.8 3.19443e-10
/gps/hist/point 1.9 3.1095e-10
/gps/hist/point 2 2.95e-10
/gps/hist/point 2.1 1.96265e-10
/gps/hist/point 2.2 2.86465e-10
/gps/hist/point 2.3 2.12054e-10
/gps/hist/point 2.4 2.81712e-10
/gps/hist/point 2.5 2.26634e-10
/gps/hist/point 2.6 2.68278e-10
/gps/hist/point 2.7 2.35011e-10
/gps/hist/point 2.8 2.55156e-10
/gps/hist/point 2.9 2.34366e-10
/gps/hist/point 3 2.45176e-10
/gps/hist/point 3.1 2.23846e-10
/gps/hist/point 3.2 2.26404e-10
/gps/hist/point 3.3 2.15964e-10
/gps/hist/point 3.4 2.17041e-10
/gps/hist/point 3.5 1.92227e-10
/gps/hist/point 3.6 1.77898e-10
/gps/hist/point 3.7 1.59691e-10
/gps/hist/point 3.8 1.54745e-10
/gps/hist/point 3.9 1.37969e-10
/gps/hist/point 4 1.25944e-10
/gps/hist/point 4.1 1.10519e-10
/gps/hist/point 4.2 1.0029e-10
/gps/hist/point 4.3 9.04693e-11
/gps/hist/point 4.4 8.12035e-11
/gps/hist/point 4.5 7.49705e-11
/gps/hist/point 4.6 6.41041e-11
/gps/hist/point 4.7 5.0251e-11
/gps/hist/point 4.8 3.99134e-11
/gps/hist/point 4.9 3.56368e-11
/gps/hist/point 5 3.47773e-11
/gps/hist/point 5.1 3.39825e-11
/gps/hist/point 5.2 3.33017e-11
/gps/hist/point 5.3 3.15277e-11
/gps/hist/point 5.4 2.726e-11
/gps/hist/point 5.5 2.20512e-11
/gps/hist/point 5.6 1.8983e-11
/gps/hist/point 5.7 1.77004e-11
/gps/hist/point 5.8 1.663e-11
/gps/hist/point 5.9 1.508e-11
/gps/hist/point 6 1.29159e-11
/gps/hist/point 6.1 1.04215e-11
/gps/hist/point 6.2 8.00399e-12
/gps/hist/point 6.3 5.93186e-12
/gps/hist/point 6.4 4.18492e-12
/gps/hist/point 6.5 2.78209e-12
/gps/hist/point 6.6 1.8373e-12
/gps/hist/point 6.7 1.33909e-12
/gps/hist/point 6.8 1.11315e-12
/gps/hist/point 6.9 9.74072e-13
/gps/hist/point 7 8.3857e-13
/gps/hist/point 7.1 7.1643e-13
/gps/hist/point 7.2 6.34594e-13
/gps/hist/point 7.3 5.8878e-13
/gps/hist/point 7.4 5.54016e-13
/gps/hist/point 7.5 5.09485e-13
/gps/hist/point 7.6 4.4571e-13
/gps/hist/point 7.7 3.62581e-13
/gps/hist/point 7.8 2.68562e-13
/gps/hist/point 7.9 1.78643e-13
/gps/hist/point 8 1.07552e-13
/gps/hist/point 8.1 6.20324e-14
/gps/hist/point 8.2 3.8973e-14
/gps/hist/point 8.3 3.01574e-14
/gps/hist/point 8.4 2.80709e-14
/gps/hist/point 8.5 2.83361e-14
/gps/hist/point 8.6 2.91269e-14
/gps/hist/point 8.7 2.98364e-14
/gps/hist/point 8.8 3.02145e-14
/gps/hist/point 8.9 3.00114e-14
/gps/hist/point 9 2.88956e-14
/gps/hist/point 9.1 2.65409e-14
/gps/hist/point 9.2 2.28317e-14
/gps/hist/point 9.3 1.80582e-14
/gps/hist/point 9.4 1.29147e-14
/gps/hist/point 9.5 8.23624e-15
/gps/hist/point 9.6 4.63235e-15
/gps/hist/point 9.7 2.27824e-15
/gps/hist/point 9.8 9.73425e-16
/gps/hist/point 9.9 3.59565e-16
/gps/hist/point 10 1.14392e-16
/gps/hist/point 10.1 3.12535e-17
/gps/hist/point 10.2 7.317e-18
/gps/hist/point 10.3 1.46535e-18
/gps/hist/point 10.4 2.5069e-19
/gps/hist/point 10.5 3.65961e-20
/gps/hist/point 10.6 4.55452e-21
/gps/hist/point 10.7 4.82897e-22
/gps/hist/point 10.8 4.35926e-23
/gps/hist/point 10.9 3.34898e-24
/gps/hist/point 11 2.1886e-25
/gps/hist/point 11.1 1.21621e-26
/gps/hist/point 11.2 5.74549e-28
/gps/hist/point 11.3 2.30678e-29
/gps/hist/point 11.4 7.86984e-31
/gps/hist/point 11.5 2.28094e-32
/gps/hist/point 11.6 5.61517e-34
/gps/hist/point 11.7 1.17399e-35
/gps/hist/point 11.8 2.08432e-37
/gps/hist/point 11.9 3.14219e-39
/gps/hist/point 12 4.02173e-41
/gps/hist/inter Lin

/random/setSeeds 5298 19704

/dmx/hitsfile ambe_spectrum.out
/dmx/histogramfile ambe_spectrum.his

/run/beamOn 10000


