###############################################################################
#                                                                             #
# PBC_Pb210.mac                                                               #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
# output log-file name
#/run/filename n_phantom_100000.log
#
# verbosities
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
##/dmx/draw/drawTracks noscint
/dmx/draw/drawTracks all
/dmx/draw/drawHits 0
#
# file output
/dmx/savePmt  0
/dmx/saveHits 0
#
#
# radioactive decay module
/grdm/analogueMC 1
/grdm/verbose 0
/grdm/allVolumes
#
#
# using GPS for ambe_spectrum:
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 12.8 0. 39.3 cm
/gps/pos/radius 5 cm
/gps/pos/halfz 3 cm
/gps/pos/confine Piezo_phys
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#
#
#
/gps/hist/point 0 2.25865e-17
/gps/hist/point 0.1 7.14826e-14
/gps/hist/point 0.2 1.4286e-13
/gps/hist/point 0.3 2.56734e-13
/gps/hist/point 0.4 4.2503e-13
/gps/hist/point 0.5 6.82076e-13
/gps/hist/point 0.6 1.39145e-13
/gps/hist/point 0.7 2.45429e-13
/gps/hist/point 0.8 4.02222e-13
/gps/hist/point 0.9 6.35501e-13
/gps/hist/point 1 9.60095e-13
/gps/hist/point 1.1 1.39393e-12
/gps/hist/point 1.2 1.95268e-12
/gps/hist/point 1.3 2.64659e-12
/gps/hist/point 1.4 3.47514e-12
/gps/hist/point 1.5 4.43497e-12
/gps/hist/point 1.6 5.52036e-12
/gps/hist/point 1.7 6.66077e-12
/gps/hist/point 1.8 7.43052e-12
/gps/hist/point 1.9 6.99579e-12
/gps/hist/point 2 5.70252e-12
/gps/hist/point 2.1 4.77058e-12
/gps/hist/point 2.2 3.83489e-12
/gps/hist/point 2.3 2.34857e-12
/gps/hist/point 2.4 9.57209e-13
/gps/hist/point 2.5 2.60974e-13
/gps/hist/point 2.6 7.71411e-14
/gps/hist/point 2.7 6.10514e-14
/gps/hist/point 2.8 7.48329e-14
/gps/hist/point 2.9 9.32846e-14
/gps/hist/point 3 1.13296e-13
/gps/hist/point 3.1 1.33073e-13
/gps/hist/point 3.2 1.4981e-13
/gps/hist/point 3.3 1.59798e-13
/gps/hist/point 3.4 1.59434e-13
/gps/hist/point 3.5 1.46878e-13
/gps/hist/point 3.6 1.23465e-13
/gps/hist/point 3.7 9.37385e-14
/gps/hist/point 3.8 6.37428e-14
/gps/hist/point 3.9 3.85626e-14
/gps/hist/point 4 2.06457e-14
/gps/hist/point 4.1 9.74161e-15
/gps/hist/point 4.2 4.03837e-15
/gps/hist/point 4.3 1.46763e-15
/gps/hist/point 4.4 4.67344e-16
/gps/hist/point 4.5 1.30949e-16
/gps/hist/point 4.6 3.30025e-17
/gps/hist/point 4.7 8.14745e-18
/gps/hist/point 4.8 2.46531e-18
/gps/hist/point 4.9 1.11217e-18
/gps/hist/point 5 6.3883e-19
/gps/hist/point 5.1 3.7427e-19
/gps/hist/point 5.2 2.05039e-19
/gps/hist/point 5.3 1.02736e-19
/gps/hist/point 5.4 4.68356e-20
/gps/hist/point 5.5 1.9398e-20
/gps/hist/point 5.6 7.29414e-21
/gps/hist/point 5.7 2.48902e-21
/gps/hist/point 5.8 7.70477e-22
/gps/hist/point 5.9 2.16286e-22
/gps/hist/point 6 5.50443e-23
/gps/hist/point 6.1 1.26973e-23
/gps/hist/point 6.2 2.6542e-24
/gps/hist/point 6.3 5.02688e-25
/gps/hist/point 6.4 8.62456e-26
/gps/hist/point 6.5 1.34024e-26
/gps/hist/point 6.6 1.8862e-27
/gps/hist/point 6.7 2.40382e-28
/gps/hist/point 6.8 2.77382e-29
/gps/hist/point 6.9 2.89788e-30
/gps/hist/point 7 2.74075e-31
/gps/hist/point 7.1 2.34649e-32
/gps/hist/point 7.2 1.81846e-33
/gps/hist/point 7.3 1.27554e-34
/gps/hist/point 7.4 8.09782e-36
/gps/hist/point 7.5 4.6527e-37
/gps/hist/point 7.6 2.4193e-38
/gps/hist/point 7.7 1.13843e-39
/gps/hist/point 7.8 4.84779e-41
/gps/hist/point 7.9 1.86793e-42
/gps/hist/point 8 6.44597e-44
/gps/hist/point 8.1 1.4013e-45
/gps/hist/point 8.2 0
/gps/hist/point 8.3 0
/gps/hist/point 8.4 0
/gps/hist/point 8.5 0
/gps/hist/point 8.6 0
/gps/hist/point 8.7 0
/gps/hist/point 8.8 0
/gps/hist/point 8.9 0
/gps/hist/point 9 0
/gps/hist/point 9.1 0
/gps/hist/point 9.2 0
/gps/hist/point 9.3 0
/gps/hist/point 9.4 0
/gps/hist/point 9.5 0
/gps/hist/point 9.6 0
/gps/hist/point 9.7 0
/gps/hist/point 9.8 0
/gps/hist/point 9.9 0
/gps/hist/point 10 0
/gps/hist/inter Lin

/random/setSeeds 5298 19704

/dmx/hitsfile ambe_spectrum.out
/dmx/histogramfile ambe_spectrum.his

/run/beamOn 10000


