###############################################################################
#                                                                             #
# Poli_U238_Up.mac                                                                #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
# output log-file name
#/run/filename n_phantom_100000.log
#
# verbosities
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
##/dmx/draw/drawTracks noscint
/dmx/draw/drawTracks all
/dmx/draw/drawHits 0
#
# file output
/dmx/savePmt  0
/dmx/saveHits 0
#
#
# radioactive decay module
/grdm/analogueMC 1
/grdm/verbose 0
/grdm/allVolumes
#
#
# using GPS for ambe_spectrum:
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0. 0. 43.21 cm
/gps/pos/radius 12.6 cm
/gps/pos/halfz 18 cm
/gps/pos/confine contenedor_HDPE_phys
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#
#
#
/gps/hist/point 0.1 1.2991e-12
/gps/hist/point 0.2 1.58345e-12
/gps/hist/point 0.3 8.21485e-13
/gps/hist/point 0.4 4.32676e-13
/gps/hist/point 0.5 6.70039e-13
/gps/hist/point 0.6 9.89196e-13
/gps/hist/point 0.7 1.40717e-12
/gps/hist/point 0.8 1.9397e-12
/gps/hist/point 0.9 2.25962e-12
/gps/hist/point 1 2.60985e-12
/gps/hist/point 1.1 3.4044e-12
/gps/hist/point 1.2 4.26865e-12
/gps/hist/point 1.3 4.51968e-12
/gps/hist/point 1.4 3.95642e-12
/gps/hist/point 1.5 4.53992e-12
/gps/hist/point 1.6 5.66875e-12
/gps/hist/point 1.7 6.92957e-12
/gps/hist/point 1.8 8.30328e-12
/gps/hist/point 1.9 9.77396e-12
/gps/hist/point 2 1.13164e-11
/gps/hist/point 2.1 1.28314e-11
/gps/hist/point 2.2 1.40298e-11
/gps/hist/point 2.3 1.46965e-11
/gps/hist/point 2.4 1.5168e-11
/gps/hist/point 2.5 1.55962e-11
/gps/hist/point 2.6 1.52733e-11
/gps/hist/point 2.7 1.37056e-11
/gps/hist/point 2.8 1.16573e-11
/gps/hist/point 2.9 1.01894e-11
/gps/hist/point 3 9.28759e-12
/gps/hist/point 3.1 8.58722e-12
/gps/hist/point 3.2 8.37741e-12
/gps/hist/point 3.3 9.09317e-12
/gps/hist/point 3.4 1.07086e-11
/gps/hist/point 3.5 1.29604e-11
/gps/hist/point 3.6 1.56894e-11
/gps/hist/point 3.7 1.88658e-11
/gps/hist/point 3.8 2.25051e-11
/gps/hist/point 3.9 2.6624e-11
/gps/hist/point 4 3.12275e-11
/gps/hist/point 4.1 3.63041e-11
/gps/hist/point 4.2 4.18211e-11
/gps/hist/point 4.3 4.77209e-11
/gps/hist/point 4.4 5.3917e-11
/gps/hist/point 4.5 6.02894e-11
/gps/hist/point 4.6 6.66779e-11
/gps/hist/point 4.7 7.28767e-11
/gps/hist/point 4.8 7.86328e-11
/gps/hist/point 4.9 8.36513e-11
/gps/hist/point 5 8.76086e-11
/gps/hist/point 5.1 9.0174e-11
/gps/hist/point 5.2 9.10398e-11
/gps/hist/point 5.3 8.99601e-11
/gps/hist/point 5.4 8.67956e-11
/gps/hist/point 5.5 8.15567e-11
/gps/hist/point 5.6 7.4434e-11
/gps/hist/point 5.7 6.58038e-11
/gps/hist/point 5.8 5.61992e-11
/gps/hist/point 5.9 4.62471e-11
/gps/hist/point 6 3.65809e-11
/gps/hist/point 6.1 2.77501e-11
/gps/hist/point 6.2 2.01477e-11
/gps/hist/point 6.3 1.39748e-11
/gps/hist/point 6.4 9.24547e-12
/gps/hist/point 6.5 5.82585e-12
/gps/hist/point 6.6 3.49226e-12
/gps/hist/point 6.7 1.98938e-12
/gps/hist/point 6.8 1.07598e-12
/gps/hist/point 6.9 5.52156e-13
/gps/hist/point 7 2.68687e-13
/gps/hist/point 7.1 1.23942e-13
/gps/hist/point 7.2 5.4198e-14
/gps/hist/point 7.3 2.2481e-14
/gps/hist/point 7.4 8.8623e-15
/gps/hist/point 7.5 3.33597e-15
/gps/hist/point 7.6 1.21245e-15
/gps/hist/point 7.7 4.36319e-16
/gps/hist/point 7.8 1.63695e-16
/gps/hist/point 7.9 6.94554e-17
/gps/hist/point 8 3.57412e-17
/gps/hist/point 8.1 2.2159e-17
/gps/hist/point 8.2 1.54835e-17
/gps/hist/point 8.3 1.14771e-17
/gps/hist/point 8.4 8.73901e-18
/gps/hist/point 8.5 6.74457e-18
/gps/hist/point 8.6 5.24969e-18
/gps/hist/point 8.7 4.11314e-18
/gps/hist/point 8.8 3.24121e-18
/gps/hist/point 8.9 2.56758e-18
/gps/hist/point 9 2.04391e-18
/gps/hist/point 9.1 1.63453e-18
/gps/hist/point 9.2 1.31281e-18
/gps/hist/point 9.3 1.05872e-18
/gps/hist/point 9.4 8.57103e-19
/gps/hist/point 9.5 6.96425e-19
/gps/hist/point 9.6 5.67837e-19
/gps/hist/point 9.7 4.64523e-19
/gps/hist/point 9.8 3.81201e-19
/gps/hist/point 9.9 3.13763e-19
/gps/hist/point 10 2.58994e-19
/gps/hist/point 10.1 2.14368e-19
/gps/hist/point 10.2 1.77894e-19
/gps/hist/point 10.3 1.47994e-19
/gps/hist/point 10.4 1.23412e-19
/gps/hist/point 10.5 1.03147e-19
/gps/hist/point 10.6 8.63976e-20
/gps/hist/point 10.7 7.25187e-20
/gps/hist/point 10.8 6.09905e-20
/gps/hist/point 10.9 1.83169e-20
/gps/hist/point 11 1.44344e-20
/gps/hist/point 11.1 2.6006e-22
/gps/hist/point 11.2 1.74169e-22
/gps/hist/point 11.3 2.3372e-25
/gps/hist/point 11.4 1.25295e-25
/gps/hist/point 11.5 2.49552e-29
/gps/hist/point 11.6 1.02702e-29
/gps/hist/point 11.7 5.51253e-34
/gps/hist/point 11.8 1.68969e-34
/gps/hist/point 11.9 2.76164e-39
/gps/hist/point 12 6.10305e-40
/gps/hist/point 12.1 9.80909e-45
/gps/hist/point 12.2 1.4013e-45
/gps/hist/point 12.3 0
/gps/hist/point 12.4 0
/gps/hist/point 12.5 0
/gps/hist/inter Lin

/random/setSeeds 5298 19704

/dmx/hitsfile ambe_spectrum.out
/dmx/histogramfile ambe_spectrum.his

/run/beamOn 20000


