###############################################################################
#                                                                             #
# SIPM_U238_UP.mac                                                          #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
# output log-file name
#/run/filename n_phantom_100000.log
#
# verbosities
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
##/dmx/draw/drawTracks noscint
/dmx/draw/drawTracks all
/dmx/draw/drawHits 0
#
# file output
/dmx/savePmt  0
/dmx/saveHits 0
#
#
# radioactive decay module
/grdm/analogueMC 1
/grdm/verbose 0
/grdm/allVolumes
#
#
# using GPS for ambe_spectrum:
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 12.2 0. 57 cm
/gps/pos/radius 2 cm
/gps/pos/halfz 2 cm
/gps/pos/confine SIPM_phys
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#
#
#
/gps/hist/point 0.1 1.48371e-11
/gps/hist/point 0.2 6.32527e-11
/gps/hist/point 0.3 5.95234e-11
/gps/hist/point 0.4 7.14691e-11
/gps/hist/point 0.5 3.83614e-11
/gps/hist/point 0.6 4.85345e-11
/gps/hist/point 0.7 5.18674e-11
/gps/hist/point 0.8 1.83989e-11
/gps/hist/point 0.9 2.85445e-13
/gps/hist/point 1 5.19569e-13
/gps/hist/point 1.1 9.0753e-13
/gps/hist/point 1.2 1.5249e-12
/gps/hist/point 1.3 2.47222e-12
/gps/hist/point 1.4 3.87718e-12
/gps/hist/point 1.5 5.89494e-12
/gps/hist/point 1.6 8.70768e-12
/gps/hist/point 1.7 1.25174e-11
/gps/hist/point 1.8 1.75413e-11
/gps/hist/point 1.9 2.39795e-11
/gps/hist/point 2 3.16864e-11
/gps/hist/point 2.1 3.84589e-11
/gps/hist/point 2.2 4.04186e-11
/gps/hist/point 2.3 4.02398e-11
/gps/hist/point 2.4 4.28542e-11
/gps/hist/point 2.5 4.46884e-11
/gps/hist/point 2.6 3.76279e-11
/gps/hist/point 2.7 2.10931e-11
/gps/hist/point 2.8 6.73735e-12
/gps/hist/point 2.9 1.08876e-12
/gps/hist/point 3 8.14647e-14
/gps/hist/point 3.1 2.65583e-15
/gps/hist/point 3.2 3.6316e-17
/gps/hist/point 3.3 2.03645e-19
/gps/hist/point 3.4 4.62167e-22
/gps/hist/point 3.5 4.21229e-25
/gps/hist/point 3.6 1.53453e-28
/gps/hist/point 3.7 2.22775e-32
/gps/hist/point 3.8 1.28637e-36
/gps/hist/point 3.9 2.95029e-41
/gps/hist/point 4 0
/gps/hist/point 4.1 0
/gps/hist/point 4.2 0
/gps/hist/point 4.3 0
/gps/hist/point 4.4 0
/gps/hist/point 4.5 0
/gps/hist/point 4.6 0
/gps/hist/point 4.7 0
/gps/hist/point 4.8 0
/gps/hist/point 4.9 0
/gps/hist/point 5 0
/gps/hist/point 5.1 0
/gps/hist/point 5.2 0
/gps/hist/point 5.3 0
/gps/hist/point 5.4 0
/gps/hist/point 5.5 0
/gps/hist/point 5.6 0
/gps/hist/point 5.7 0
/gps/hist/point 5.8 0
/gps/hist/point 5.9 0
/gps/hist/point 6 0
/gps/hist/point 6.1 0
/gps/hist/point 6.2 0
/gps/hist/point 6.3 0
/gps/hist/point 6.4 0
/gps/hist/point 6.5 0
/gps/hist/point 6.6 0
/gps/hist/point 6.7 0
/gps/hist/point 6.8 0
/gps/hist/point 6.9 0
/gps/hist/point 7 0
/gps/hist/point 7.1 0
/gps/hist/point 7.2 0
/gps/hist/point 7.3 0
/gps/hist/point 7.4 0
/gps/hist/point 7.5 0
/gps/hist/point 7.6 0
/gps/hist/point 7.7 0
/gps/hist/point 7.8 0
/gps/hist/point 7.9 0
/gps/hist/point 8 0
/gps/hist/point 8.1 0
/gps/hist/point 8.2 0
/gps/hist/point 8.3 0
/gps/hist/point 8.4 0
/gps/hist/point 8.5 0
/gps/hist/point 8.6 0
/gps/hist/point 8.7 0
/gps/hist/point 8.8 0
/gps/hist/point 8.9 0
/gps/hist/point 9 0
/gps/hist/point 9.1 0
/gps/hist/point 9.2 0
/gps/hist/point 9.3 0
/gps/hist/point 9.4 0
/gps/hist/point 9.5 0
/gps/hist/point 9.6 0
/gps/hist/point 9.7 0
/gps/hist/point 9.8 0
/gps/hist/point 9.9 0
/gps/hist/point 10 0
/gps/hist/point 10.1 0
/gps/hist/point 10.2 0
/gps/hist/point 10.3 0
/gps/hist/point 10.4 0
/gps/hist/point 10.5 0
/gps/hist/point 10.6 0
/gps/hist/point 10.7 0
/gps/hist/point 10.8 0
/gps/hist/inter Lin

/random/setSeeds 5298 19704

/dmx/hitsfile ambe_spectrum.out
/dmx/histogramfile ambe_spectrum.his

/run/beamOn 20000


